baseinfo/urls.py
from django.urls import path
from .views import (get_contracts_list_view,
                    AddContractView,
                    get_employers_list_view,
                    AddEmployerView,
                    get_banks,
                    AddBankView,
                    CompanyInfo_View)
app_name = 'baseinfo'
urlpatterns=[
    path("contracts/", get_contracts_list_view, name = "contract-list"),
    path("contract/create/", AddContractView.as_view(), name = "contract-create"),
    path('employers/', get_employers_list_view, name = "employer-list"),
    path("employer/create/", AddEmployerView.as_view(), name = "employer-create"),
    path("banks/", get_banks, name = "bank-list"),
    path("bank/create/",AddBankView.as_view(), name = "bank-create" ),
    path("companyInfo",CompanyInfo_View.as_view(),name = "companyInfo-list"),
]

tax/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import static
from django.views.generic import TemplateView


admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc', include('django.contrib.admindocs.urls')),
    path('',include('pages.urls')),
    path('documents/',include('docmanagment.urls')),
    path('baseinfo/',include('baseinfo.urls')),
    path('income/',include('income.urls')),
    path('accounts/',include('accounts.urls')),
    ]

baseinfo/models.py
from django.db import models
from django.contrib.auth.admin import User

class FinancialYear(models.Model):
    year           =   models.IntegerField('سال مالی')
    is_deleted     =   models.BooleanField()
    description    =   models.TextField('توضیحات')

    def __str__(self):
        return str(self.year)

class City(models.Model):
    name            =   models.CharField('نام شهر', max_length=50)

    def __str__(self):
        return self.name

class Bank(models.Model):
    title           =   models.CharField('نام بانک',max_length=50)
    branch_name     =   models.CharField('نام شعبه',max_length=50)
    account_number   =   models.CharField('شماره حساب',max_length=50)
    shaba_number    =   models.CharField('شماره شبا',max_length=27)

    def __str__(self):
        return "{}-{}".format(self.title,self.account_number)
        

class Employer(models.Model):
    title           =   models.CharField('نام کارفرما',max_length=50)
    national_code   =   models.CharField('شناسه ملی',max_length=11)
    economic_id     =   models.CharField('شماره اقتصادی',max_length=11)
    phone_number    =   models.CharField("شماره تلفن",max_length=11)
    city_name       =   models.ForeignKey(City,verbose_name="شهر",null=True,on_delete=models.SET_NULL)
    address         =   models.TextField(verbose_name="آدرس")
    description     =   models.CharField('توضیحات',max_length=100,null=True,blank=True)

    def get_abseloute_url(self):
        return f"/employers/{self.id}"

    def __str__(self):
        return self.title


class Contract(models.Model):
    employer    =   models.ForeignKey(Employer,verbose_name="کارفرما",on_delete=models.CASCADE)
    title       =   models.CharField('عنوان قرارداد',max_length=100)
    number      =   models.CharField('شماره قرارداد',max_length=50)
    date        =   models.DateField('تاریخ شروع',)
    end_date    =   models.DateField('تاریخ پایان',null=True,blank=True)
    gross_amount=   models.DecimalField('مبلغ اولیه قرارداد',max_digits=20,decimal_places=2,default=0)
    adjustment_amount=   models.DecimalField('مبلغ تعدیل',max_digits=20,decimal_places=2,default=0)
    final_amount=   models.DecimalField('مبلغ نهایی قرارداد',max_digits=20,decimal_places=2,default=0)
    total_payments=   models.DecimalField('مجموع مبالغ دریافتی',max_digits=20,decimal_places=2,default=0)
    progress    =   models.DecimalField('درصد پیشرفت',max_digits=10,decimal_places=2,default=0)
    scan_file   =   models.FileField('فایل قرارداد',blank=True,upload_to='income/static/contracts')
    description =   models.CharField('توضیحات',blank=True,max_length=100)

    def __str__(self):
        return self.title


class Guarantee(models.Model):
    GUARANTEE_TYPE=[
        (1," ضمانت نامه شرکت در مناقصه"),
        (2," ضمانت نامه پیش پرداخت"),
        (3," ضمانت نامه حسن انجام کار"),
    ]

    GUARANTEE_STATUS=[
        (1,"صدور"),
        (2,"ابطال شد"),
        (3,"تمدید"),
        
    ]
    
    employer        = models.ForeignKey(Employer,verbose_name="کارفرما",on_delete = models.DO_NOTHING)
    contract        = models.ForeignKey(Contract,verbose_name="عنوان قرارداد",on_delete=models.CASCADE)
    guarantee_type  = models.IntegerField("عنوان ضمانت نامه",choices=GUARANTEE_TYPE)
    guarntee_number = models.CharField("شماره ضمانت نامه",max_length=60,blank=True,null=True)
    guarntee_Sepam  = models.CharField("شماره سپام",max_length=60,blank=True,null=True)
    bank            = models.ForeignKey(Bank,verbose_name="نام بانک",on_delete=models.DO_NOTHING) 
    amount          = models.DecimalField("مبلغ ضمانت نامه",max_digits=20,decimal_places=0,default=0)
    status          = models.IntegerField("وضعیت ضمانت نامه",choices=GUARANTEE_STATUS)
    parent_guarantee = models.ForeignKey("self",verbose_name= "ضمانت نامه اصلی",
                    on_delete=models.DO_NOTHING,null=True,blank=True)
    issue_date   = models.DateField("تاریخ صدور")
    expire_date  = models.DateField("تاریخ انقضاء")
    guarantee_file = models.FileField("فایل ضمانت نامه",blank=True,null=True)
    added_by     = models.ForeignKey(User,verbose_name="ایجاد کننده",on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.get_guarantee_type_display()}-{self.contract}"

class CompanyInfo(models.Model):
    name            =   models.CharField('نام شرکت',max_length=50)
    register_number =   models.CharField('شماره ثبت',max_length=20)
    register_date   =   models.DateField('')
    national_code   =   models.CharField('شناسه ملی',max_length=11)
    economic_id     =   models.CharField('شماره اقتصادی',max_length=12)
    phone_number    =   models.CharField("شماره تلفن",max_length=11)
    city_name       =   models.ForeignKey(City,verbose_name="شهر",null=True,on_delete=models.SET_NULL)
    address         =   models.TextField(verbose_name="آدرس")
    email           =   models.EmailField("ایمیل",blank=True,null=True)
    site            =   models.URLField("آدرس سایت",blank=True,null=True)
    description     =   models.CharField('توضیحات',max_length=100,null=True,blank=True)

    def __str__(self):
        return f"{self.name}"

class Person(models.Model):
    POSITION=[
        (1,"مدیرعامل"),
        (2,"رییس هییت مدیره"),
        (3,"نایب رییس هییت مدیره"),
        (4,"عضور"),
        ]
    DEGREE=[
        (1,"دیپلم"),
        (2,"کاردانی"),
        (3,"کارشناسی"),
        (4,"کارشناسی ارشد"),
        ]
    FIELD_OF_STUDY=[
        (1,"عمران"),
        (2,"مکانیک"),
        (3,"کامپیوتر"),
        (4,"برق"),
        (5,"معماری"),
    ]
    company         =   models.ForeignKey(CompanyInfo,verbose_name="نام شرکت",on_delete=models.DO_NOTHING)
    fname           =   models.CharField("نام",max_length=50)
    lname           =   models.CharField("نام خانوادگی",max_length=50)
    father_name     =   models.CharField("نام پدر",max_length=50)
    national_code   =   models.CharField("کد ملی",max_length=10)
    id_number       =   models.CharField("شماره شناسنامه",max_length=10)
    position        =   models.IntegerField("سمت",choices=POSITION)
    number_of_shares=   models.IntegerField("تعداد سهم",default=0)
    degree          =   models.IntegerField("مدرک تحصیلی",choices=DEGREE)
    work_experience =   models.IntegerField("سابقه کار")
    field_of_study  =   models.IntegerField("",choices=FIELD_OF_STUDY)
    tel             =   models.CharField("شماره تلفن",max_length=20,blank=True,null=True)
    address         =   models.TextField("آدرس",blank=True,null=True)
    is_deleted      =   models.BooleanField(default=False)

    def __str__(self):
        return f"{self.fname}-{self.lname}"

baseinfo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from views_generator import ViewGenerator
from django.db.models import Sum
from income.models import Income
from django.views.generic import FormView,CreateView,ListView
from .froms import *
from .models import *

# Contract list view
def get_contracts_list_view(request,*args,**kwargs):
    
   contracts=Contract.objects.all()
   for contract in contracts:
       contract_amount=contract.gross_amount + contract.adjustment_amount
       incomes=Income.objects.filter(contract=contract)
       total_income=incomes.aggregate(Sum('gross_amount'))
       contract.total_payments=total_income['gross_amount__sum']
       contract.final_amount=contract_amount
       if contract.total_payments is not None:
        contract.progress='{0:.3g}'.format(total_income['gross_amount__sum']/contract_amount)
       else:
        contract.total_payments=0
        contract.progress=0

       contract.save()
    

   view=ViewGenerator(table=Contract,
                     opration_buttons={},select_checkbox=False,add_url='baseinfo:contract-create')
   return render(request,"baseinfo/contracts_list.html",view.get_context_template())  

# Create contract view
class AddContractView(FormView):
    template_name   =   'share/input_form.html'
    form_class      =   AddContractForm
    success_url     =   reverse_lazy('contract-list')
    
    def form_valid(self, form):
        form.save_record()
        return super().form_valid(form)

# Employers list view
def get_employers_list_view(request,*args,**kwargs):
    view=ViewGenerator(table=Employer,opration_buttons={},select_checkbox=False,
                        add_url='baseinfo:employer-create')
    return render(request,"baseinfo/employer_list.html",view.get_context_template())

# Create employer view
class AddEmployerView(FormView):
    template_name   =   'share/input_form.html'
    form_class      =   AddEmployerForm
    success_url     =   reverse_lazy('employers')

    def form_valid(self, form):
        form.save_record()
        return super().form_valid(form)

# Update employer view
def update_employer_view(request,id):
    if request.method=='POST':
        employer=Employer.objects.get(id=id)
        form=AddEmployerForm(employer)


# Bank list view
def get_banks(request,*args,**kwargs):
    
    view=ViewGenerator(table=Bank,opration_buttons={},
                        select_checkbox=False,add_url='baseinfo:bank-create')

    return render(request,"share/list.html",view.get_context_template())

# Create bank view
class AddBankView(FormView):
    template_name   =   'share/input_form.html'
    form_class      =   BankForm
    success_url     =   reverse_lazy('baseinfo:bank-list')
    
    def form_valid(self, form):
        form.save_record()
        return super().form_valid(form)

#Create company vie

class CompanyInfo_View(ListView):
    model = CompanyInfo
    template_name   =   "baseinfo/companyInfo.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data(**kwargs)
        persons=Person.objects.filter(company=1)
        context['persons']=persons
        return context


    

templates/baseinfo/companyInfo.html
{% extends "share/base.html" %}
{% load getattribute %}
{% load l10n %}
{% load jformat %}

{% block content %}

<div class="row ">
    <div class="col-md-8 col-sm-6 border text-center">
        اعضای هییت مدیره
        <table class="table">
            <tr>
                <th>نام</th>
                <th>نام خانوادگی</th>
                <th>نام پدر</th>
                <th>کد ملی</th>
                <th>سمت</th>
                <th>تعداد سهام</th>
                <th>مدرک تحصیلی</th>
            </tr>
            {% for person in persons %}
            <tr>
                <td>{{person.fname}}</td>
                <td>{{person.lname}}</td>
                <td>{{person.father_name}}</td>
                <td>{{person.national_code}}</td>
                <td>{{person.get_position_display}}</td>
                <td>{{person.number_of_shares}}</td>
                <td>{{person.get_degree_display}}</td>
            </tr>
            {% endfor %}
        </table>
        <table class="table">
            اطلاعات تماس
            <tr>
                <th>ایمیل</th>
                <th>تلفن</th>
                <th>سایت</th>
                <th>آدرس</th>
            </tr>
            <tr>
                <td>{{object_list.0.email}}</td>
                <td>{{object_list.0.phone_number}}</td>
                <td>{{object_list.0.site}}</td>
                <td>{{object_list.0.address}}</td>
            </tr>
        </table>
    </div>
    <div class="col-md-4 col-sm-6 border text-center">
        <table class="table">
           اطلاعات مالی
            <tr>
                <th>شناسه ملی</th>
                <th>کد اقتصادی</th>
            </tr>
            <tr>
                <td>{{object_list.0.national_code}}</td>
                <td>{{object_list.0.economic_id}}</td>
            </tr>
        </table>
    </div>
</div>

{% endblock %}

templates/baseinfo/contracts_list.html
{% extends "share/base.html" %}
{% load getattribute %}
{% load l10n %}
{% load jformat %}

{% block content %}

    <div id='page_top'></div>
    <a href="{% url add_url_name %}" class="btn rounded btn-dark bg-dark my-5 my-sm-0" target="blank">جدید</a>
    <div id='data-list'>
        <table class="table">
            <tr>
                <!-- if select checkbox is tru you will seel check box in the first of all rows-->
                {% if select_checkbox %}
                <th><input type="checkbox">همه</th>
                {% endif %}

                {% for title in titles %}
                <th>
                    {{title}}
                </th>
                {% endfor %}

                <!-- if opration button is true the you will see opration button in last col -->
                {% if opration_buttons %}
                <th>عملیات</th>
                {% endif %}

            </tr>
            <!-- check if exist any object -->
            {% if objects %}
            <!-- loop through objects for display in html file -->
            {% for object in objects %}
            <tr>
                <!-- if opration button is true the you will see opration button in last col -->
                {% if select_checkbox %}
                    <td><input type="checkbox"></td>
                {% endif %}
                <td>{{forloop.counter}}</td>

                {% for field in field_names %}
                    {% if field == "year" %}<!--check if field is year the disable separator for it-->
                        {% localize off %}
                            <td>{{ object|getattribute:field }}</td>
                        {% endlocalize %}

                        {% elif field == "date" %}<!--check if field is year the disable separator for it-->
                        {% localize off %}
                            <td>{{ object|getattribute:field|jformat:"%Y/%m/%d" }}</td>
                        {% endlocalize %}

                        {% elif field == "progress" %}
                                {% if object.progress >= 1  %}
                                    <td style="background-color: #36f" >{{ object|getattribute:field }}</td>
                                {% else %}
                                     <td style="background-color: indianred">{{object.progress}}</td>
                                {% endif %}
                    {% else %}
                        <td>{{ object|getattribute:field }}</td>
                    {% endif %}
                {% endfor %}

                <!-- if opration button is true the you will see opration button in last col -->
                {% if opration_buttons %}
                <td>
                    {% for key,values in opration_buttons.items %}
                    <a class='opration_btn' href="{% url values.1 id=object.id %}" name={{object.id}}
                        onclick={{key}}>{{values.0}}</a>
                    {% endfor %}
                </td>
                {% endif %}

            </tr>
            {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/baseinfo/employer_list.html
{% extends "share/base.html" %}
{% load getattribute %}
{% load l10n %}
{% load jformat %}

{% block content %}

    <div id='page_top'></div>
    <a href="#page_top" id="jump-top" class="fa fa-angle-up fa-4x-up"></a>
    <a href="{% url add_url_name %}" class="button" target="blank">جدید</a>
    <div id='data-list'>
        <table class="table table-hover">

            <!-- Add Header Row. -->
            <tr>
                <!-- if select checkbox is tru you will seel check box in the first of all rows-->
                {% if select_checkbox %}
                    <th><input type="checkbox">همه</th>
                {% endif %}

                <!-- Add Header row by nams of table fields. -->
                {% for title in titles %}
                <th>
                    {{title}}
                </th>
                {% endfor %}

                <!-- if opration button is true the you will see opration button in last col -->
                {% if opration_buttons %}
                    <th>عملیات</th>
                {% endif %}

            </tr>

            <!-- check if exist any object -->
            {% if objects %}
            <!-- loop through objects for display in html file -->
                {% for object in objects %}
                    <tr id={{object.id}}>
                        <!-- if opration button is true the you will see opration button in last col -->
                        {% if select_checkbox %}
                            <td><input type="checkbox"></td>
                        {% endif %}

                        <!-- Add row number for each object. -->
                        <td>{{forloop.counter}}</td>

                        <!-- Add field value. -->
                        {% for field in field_names %}

                            {% if field == "year" %}
                                {% localize off %}
                                    <td>{{ object|getattribute:field }}</td>
                                {% endlocalize %}
                            {% elif field == "title" %}
                                 <td><a href="{{    'contracts id=object.id'    }}"> {{ object|getattribute:field }} </a></td>
                            {% else %}
                                <td>{{ object|getattribute:field }}</td>
                            {% endif %}
                        {% endfor %}

                        <!-- Add opration button in last column. -->
                        {% if opration_buttons %}
                        <td>
                            {% for key,values in opration_buttons.items %}
                            <a class='opration_btn' href="{% url values.1 id=object.id %}" name={{object.id}}
                                onclick={{key}}>{{values.0}}</a>
                            {% endfor %}
                        </td>
                        {% endif %}

                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}