accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns=[
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
]

baseinfo/urls.py
from django.urls import path
from .views import (get_contracts_list_view,
                    AddContractView,
                    get_employers_list_view,
                    AddEmployerView,
                    get_banks,
                    AddBankView,
                    CompanyInfo_View)
app_name = 'baseinfo'
urlpatterns=[
    path("contracts/", get_contracts_list_view, name = "contract-list"),
    path("contract/create/", AddContractView.as_view(), name = "contract-create"),
    path('employers/', get_employers_list_view, name = "employer-list"),
    path("employer/create/", AddEmployerView.as_view(), name = "employer-create"),
    path("banks/", get_banks, name = "bank-list"),
    path("bank/create/",AddBankView.as_view(), name = "bank-create" ),
    path("companyInfo",CompanyInfo_View.as_view(),name = "companyInfo-list"),
]

income/urls.py
from django.urls import path
from .views import *

app_name = 'income'

urlpatterns=[
    path("",get_incomes_view, name = "income-list"),
    path("create/", AddIncomeView.as_view(), name = "income-create"),
    path("buys/",get_buys_view, name = "buy-list"),
    path("buy/create/", AddBuyView.as_view(),name="buy-create"),
    path("season-report/",get_season_view,name="season-report"),
    path("employer-pays/",get_employer_payment_view,name="employer-pays"),
    path("contract-pays/",get_contract_payments_view,name="contract-pays"),
    path("declaration/",declaration_view,name="declaration"),
    path('employer-contracts/<int:id>',get_contracts_view,name="employer-contracts"),
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as Auth_Views
from .views import *

app_name='pages'

urlpatterns=[
    path('',home,name='home'),
    path('login/',Auth_Views.LoginView.as_view(template_name='pages/login.html')),
    path('logout/',Auth_Views.LogoutView.as_view(template_name='pages/home.html')),
]

tax/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import static
from django.views.generic import TemplateView


admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc', include('django.contrib.admindocs.urls')),
    path('',include('pages.urls')),
    path('documents/',include('docmanagment.urls')),
    path('baseinfo/',include('baseinfo.urls')),
    path('income/',include('income.urls')),
    path('accounts/',include('accounts.urls')),
    ]

templates/share/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<meta charset="utf-8">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}">
    <meta charset="utf-8">
    <title>سیستم اتوماسیون شرکت آروین کیان سازه</title>
  </head>
  <body>
      {% include "share/navbar.html" %}
      <br><br><br>
      {% block content %} {% endblock %}
      
  </body>


<!-- Bootstarp dependencys -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    
</html>

templates/share/input_form.html
{% extends "share/base.html" %}
{% load getattribute %}
{% load l10n %}
{% load jformat %}
{% block content %}

<form class="form-group" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">ذخیره</button>
</form>

{% endblock %}

templates/share/list.html
{% extends "share/base.html" %}
{% load getattribute %}
{% load l10n %}
{% load jformat %}

{% block content %}

<a href="{% url add_url_name %}" class="btn btn-dark" target="blank">جدید</a>
<div id='data-list'>
    <table class="table table-striped mt-4">
      <tr>
        <!-- if select checkbox is tru you will seel check box in the first of all rows-->
        {% if select_checkbox %}
        <th><input type="checkbox">همه</th>
        {% endif %}

        {% for title in titles %}
        <th>
          {{title}}
        </th>
        {% endfor %}

        <!-- if opration button is true the you will see opration button in last col -->
        {% if opration_buttons %}
        <th>عملیات</th>
        {% endif %}

      </tr>
      <!-- check if exist any object -->
      {% if objects %}
      <!-- loop through objects for display in html file -->
      {% for object in objects %}
      <tr>
        <!-- if opration button is true the you will see opration button in last col -->
        {% if select_checkbox %}
        <td><input type="checkbox"></td>
        {% endif %}
        <td>{{forloop.counter}}</td>

        {% for field in field_names %}
        {% if field == "year" %}
        <!--check if field is year the disable separator for it-->
        {% localize off %}
        <td>{{ object|getattribute:field }}</td>
        {% endlocalize %}

        {% elif field == "date" %}
        <!--check if field is year the disable separator for it-->
        {% localize off %}
        <td>{{ object|getattribute:field|jformat:"%Y/%m/%d" }}</td>
        {% endlocalize %}

        {% else %}
        <td>{{ object|getattribute:field }}</td>
        {% endif %}
        {% endfor %}

        <!-- if opration button is true the you will see opration button in last col -->
        {% if opration_buttons %}
        <td>
          {% for key,values in opration_buttons.items %}
          <a class='opration_btn' href="{% url values.1 id=object.id %}" name={{object.id}} onclick={{key}}>{{values.0}}</a>
          {% endfor %}
        </td>
        {% endif %}

      </tr>
      {% endfor %}
      {% endif %}
    </table>
  </div>
{% endblock %}

templates/share/navbar.html
<nav class="navbar navbar-dark navbar-expand-sm bg-dark fixed-top">
  <a class="navbar-brand " href="#">شرکت آروین کیان سازه</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'pages:home' %}">خانه<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          اطلاعات پایه
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'baseinfo:companyInfo-list' %}">اطلاعات شرکت</a>
          <a class="dropdown-item" href="{% url 'baseinfo:employer-list' %}">اطلاعات کارفرمایان</a>
          <a class="dropdown-item" href="{% url 'baseinfo:contract-list' %}">اطلاعات قراردادها</a>
          <a class="dropdown-item" href="{% url 'baseinfo:bank-list'     %}">اطلاعات حسابها</a>
          <a class="dropdown-item" href="{% url 'income:income-list'     %}">اطلاعات درآمدها</a>
          <a class="dropdown-item" href="{% url 'income:buy-list'        %}">اطلاعات خریدها</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          گزارشات
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'income:declaration'    %}">اظهارنامه مالیاتی</a>
          <a class="dropdown-item" href="#">اظهارنامه ارزش افزوده</a>
          <a class="dropdown-item" href="{% url 'income:season-report'  %}">اظهارنامه ماده 169</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">تماس</a>
      </li>



      <form class="form-inline">
        <input class="form-control mr-md-2 mx-lg-1 ml-sm-0" type="search" placeholder="جستجو" aria-label="جستجو">
        <button class="btn btn-outline-light bg-dark my-5 my-sm-0" type="submit">جستجو</button>
      </form>
      {% if user.is_authenticated %}
      <a href="{% url 'pages:home' %}" class="nav-link mr-auto">{{user.username}}خوش آمدید</a>
      <li class="nav-item ml-3">
        <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
          <i class="fas fa-sign-out-alt"></i> خروج
        </a>
        <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
          {% csrf_token %}
          <input type="hidden" >
        </form>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'accounts:register' %}">ثبت نام</a>
      </li>
      {% endif %}


    </ul>

  </div>

</nav>

templates/share/navbar0.html
{% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}">
<title>This is chapar website</title>

<body>
    <div class="navbar navbar-default navbar-fixed-top navbar-dark bg-dark" id="topNavbar" >

        <a href="#" class="main-item" onclick="showDropdwonMenu('baseinfo')">اطلاعات پایه</a>
        <div id="baseinfo" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick=" closeNav('baseinfo')">&times;</a>
            <div class="overlay-content">
                <div class="column">
                    <a href="{% url 'baseinfo:employer-list' %}">اطلاعات کارفرمایان</a>
                    <a href="{% url 'baseinfo:contract-list' %}">اطلاعات قراردادها</a>
                    <a href="{% url 'baseinfo:bank-list'     %}">لیست بانک ها</a>
                    <a href="{% url 'income:income-list' %}">لیست درآمدها</a>
                    <a href="{% url 'income:buy-list' %}">لیست خریدها</a>
                    <a href="{% url 'docmanagment:document-list' %}"> اسناد و مدارک</a>

                </div>
                <div class="column">
                    <a href="{{ 'home'          }}">ثابتها</a>
                    <a href="{{ 'home'          }}">اطلاعات کارکنان</a>
                    <a href="{{ 'home'          }}">لیست گروه های شغلی</a>
                    <a href="{{ 'home'          }}">لیست محل های کاری</a>
                    <a href="{{ 'home'          }}">لیست پست ها</a>
                </div>
            </div>
        </div>

        <a href="#" class="main-item" onclick="showDropdwonMenu('wageNav')">حقوق ودستمزد</a>
        <div id="wageNav" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick=" closeNav('wageNav')">&times;</a>
            <div class="overlay-content">
                <a href="{{ 'home'          }}">مشاهده لیست های حقوق</a>
                <a href="{{ 'home'          }}">لیست وام و مساعده</a>
                <a href="{{ 'home'          }}">ایجاد فایل پرداخت</a>
                <a href="{{ 'home'          }}">چاپ فیش ماهیانه</a>
                <a href="{{ 'home'          }}">چاپ لیست مالیات</a>
            </div>
        </div>

        <a href="#" class="main-item" onclick="showDropdwonMenu('attendNav')">حضور وغیاب</a>
        <div id="attendNav" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick=" closeNav('attendNav')">&times;</a>
            <div class="overlay-content">
                <a href="#">لیست حضور وغیاب ماه جاری</a>
                <a href="#">ایجاد حضور وغیاب</a>
                <a href="#">آنالیز حضور و غیاب</a>
                <a href="#">چاپ حضور و غیاب ماه جاری</a>
                <a href="#">ایجاد فایل حضور و غیاب</a>
                <a href="#">ورود اطلاعات حضور و غیاب</a>
            </div>
        </div>

        <a href="#" class="main-item" onclick="showDropdwonMenu('reportNav')">گزارشات</a>
        <div id="reportNav" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick=" closeNav('reportNav')">&times;</a>
            <div class="overlay-content">
                <a href="{% url 'income:season-report'  %}">گزارش عملکرد فصول</a>
                <a href="{% url 'income:employer-pays'  %}">گزارش مالی بر اساس کارفرما</a>
                <a href="{% url 'income:contract-pays'  %}">گزارش مالی بر اساس قرارداد</a>
                <a href="{% url 'income:declaration'    %}">اظهارنامه</a>

                <a href="#">چاپ حضور و غیاب ماه جاری</a>
                <a href="#">ایجاد فایل حضور و غیاب</a>
                <a href="#">ورود اطلاعات حضور و غیاب</a>
            </div>
        </div>
        <input type="text" id="searchTextbox" name='search_value' placeholder="متن مورد نظر را وارد کنید...">
        <a href=# class='main-item'><i class="fa fa-fw fa-search"></i>جستجو</a>

        <a href="#" class="main-item" style="float:left;">+ ورود</a>

    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script>

        var opened_menu = '';

        function showDropdwonMenu(menuName) {
            if (opened_menu!=''){
                closeNav(opened_menu)
            }
            document.getElementById(menuName).style.width = "20%";
            opened_menu = menuName;
            document.body.style.marginRight = "20%"

        }

        function closeNav(naveName) {
            document.getElementById(naveName).style.width = "0";
            document.body.style.marginRight = "0"
        }


        document.addEventListener('click',(evt)=>{
            if(evt.target==document.body){
                closeNav(opened_menu);
            }
        })







    </script>